### ISSUE TITLE
FastChem seg faults

### ISSUE THREAD

**Issue by ideasrule** [NewStrangeWorlds/FastChem#5]
When I use this as the PT profile:

> 1e-3    150

...but without changing anything else in input/config.input, the code segmentation faults:

> $ ./fastchem input/config.input
> malloc(): invalid next size (unsorted)
> Aborted (core dumped)

When I change the "FastChem console verbose level" to 4, I get:

> Too large n_min and n_maj for species Cl. Switching to backup.  Iteration step: 0
> FastChem: WARNING: NewtSol Alt failed for species Ge switched to Bisection as backup 0	4.82864e+16
> (previous line repeats 62 times)
> malloc(): invalid next size (unsorted)
> Aborted (core dumped)

Why does NewtSol fail?  And why does a NewtSol failure make the code segfault?

**Comment by cvbuchem** [comment]
I get the same error when running over a large TP grid (the one used in the [HELIOS tutorial](https://heliosexo.readthedocs.io/en/latest/sections/tutorial.html)). When I try running the same TP profile through pyfastchem i get a similar error:

`munmap_chunk(): invalid pointer`
`Aborted (core dumped)`

When using the TP profile included originally the code runs properly.

**Comment by daniel-kitzmann** [comment]
Sorry for the late answer, I didn't notice that someone posted an issue. It was a minor problem that is fixed now.
Thanks for reporting the error!
